name: MallProtect
version: ${project.version}
main: com.github.showwno.mallprotect.MallProtect
api-version: 1.13

commands:
  protect:
    usage: /protect
    description: hane server asist plugin

  protect.*:
    description: Gives access to all commands
    default: op
